language: ruby
rvm:
  - ruby-head
before_install:
  - wget ftp://crisp.dyndns-server.com/pub/release/website/dtrace/dtrace-20131103.tar.bz2
  - bunzip2 < dtrace-20131103.tar.bz2 | tar xvf -
install:
  - sudo apt-get update
  - sudo apt-get install bison
  - sudo apt-get install flex
  - sudo apt-get install zlib1g-dev
  - sudo apt-get install libelf-dev
  - cd dtrace-20131103
  - make all
  - sudo make install
  - sudo make load
before_script:
  - sudo dtrace -V
